database models for incidents and laws
hack4impact-uiuc/collective-liberty pull request #15
Opened 2020-10-06 00:30 UTC by kellydunleavy

### Changes
* Add data model for trafficking incident
* Add data model for trafficking law
---
### Screenshots (if UI change)

2020-10-06 01:53 UTC, rxun requested changes
for incident:
- dateOfOperation feels like it should be a Date type rather than a String -- i'm not sure if we need a separate field for "end date operation" because some entries have two dates
- operationType has a typo after "type: String"
- why include criminal charges but not civil/code charges? i think we can remove criminalCharges as a field

for law, it looks good for now, depending on what we do for the future!

2020-10-16 21:42 UTC, rxun reviewed
sorry -- remove civilCodeCharges from incident schema and you're good to merge

2020-10-17 05:01 UTC, kellydunleavy commented
Kendall indicated that the start and end date of operation fields may remain as Strings, which is why my revisions do not include that feedback.

2020-10-20 01:43 UTC, rxun approved these changes

2020-10-20 01:49 UTC, merged