Added zoom controls, search bar, and legend to map
hack4impact-uiuc/collective-liberty pull request #27
Opened 2020-10-20 03:04 UTC by abetco

### Changes
Added zoom controls, search bar, and legend to map

### Screenshots (if UI change)
---
### Checklist
- [ ] Added a11y fields (if applicable)

2020-10-23 22:23 UTC, kellydunleavy approved these changes
this looks great!

2020-10-23 22:24 UTC, rxun requested changes
i think what's there looks good, but check with siraj for final confirmation on css. i would be careful because right now on the preview, if you double click the icon / legend, it'll zoom in, so i would try and prevent that behavior. if you check the figmas as well, i believe siraj has added another set of toggles in the bottom left (i'd ask for updates from him) which should be fairly quick. i added some notes about a11y but looks good overall

2020-10-23 22:24 UTC, rxun commented on client/src/components/Map.jsx
> +        style={{ position: "absolute", left: 20, top: 20 }}
not totally sure, but it is possible that you would want to put `role='search'` in this div, then for the aria-labels for input and button inside, you would remove redundant "search" words --> ie) `aria-label="Submit search" `would turn into `aria-label="Submit"`
reference: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Search_role

2020-10-23 22:24 UTC, rxun commented on client/src/components/Map.jsx
> +            <img src="legend.png" alt="legend" />
probably something more descriptive is useful here -- for example, we would want to say `alt="Individual Arrests 0 to 30+"`

2020-10-27 02:37 UTC, rxun approved these changes

2020-10-27 02:39 UTC, merged