🍊 Tabs on sidebar
hack4impact-uiuc/collective-liberty pull request #78
Opened 2020-12-01 03:05 UTC by lucianatl

### Changes

- added arrest, massage parlor, laws vacatur laws and criminal law tabs on sidebar
- tried to add orange bar at the bottom to match the Figma and make it look like tabs, however yarn stopped working before I was able to finish that part so I currently I have no idea how it looks 
- no screenshots even though there was a a UI change bc of above problem 

---

### Screenshots (if UI change)

---

### Checklist

- [ ] Added a11y fields (if applicable)

2020-12-01 03:43 UTC, rxun approved these changes
good work! the ui is functional, but just clean up some of the design (and the small nit i ahd)
my concern comes with whether or not tab changes will be accessible since visibility / toggling states doesn't necessarily alert the user in react, i think?? don't worry about it now, i'll place it into the running list of a11y things we'd like to look over later

2020-12-01 03:43 UTC, rxun commented on client/src/components/SidebarContainer.jsx
> +          aria-label="Criminal Law"
nit: change "Criminal Law" to "Criminal Laws"

2020-12-01 03:46 UTC, kenetec requested changes
some small changes for the code

2020-12-01 03:46 UTC, kenetec commented on client/src/components/SidebarContainer.jsx
> +  const [tab, setTab] = useState(0);
Can we move tab to `MapPage.jsx` and make constants for all values of the tab var (0...3), that way we can update the map when the user switches tabs.

2020-12-01 03:46 UTC, kenetec commented on client/src/components/SidebarContainer.jsx
> +          style={{ 'background-color': tab === 0 ? 'darkorange' : 'grey' }}
Replace all comparisons with `tab` with constants

2020-12-02 02:16 UTC, kenetec approved these changes
littyyy 🤩💯

2020-12-02 03:49 UTC, merged